### ISSUE TITLE
Nginx as proxy server to map traffic based on URI

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/NoOps#1]
AS A DevOps
I WANT to map traffic based on defined rules
SO THAT I could use different (versions of) components

### Acceptance Criteria

- [ ] Based on Nginx
- [ ] http://admin.test.buerokratt.ee redirects to http://admin.test.buerokratt.ee/chat
- [x] "Vestlus / Chat" of [Backoffice GUI](https://github.com/buerokratt/Buerokratt-Chatbot/tree/main/GUI
) responds to http://admin.test.buerokratt.ee/chat
- [ ] "Settings / Haldus" of [Backoffice GUI](https://github.com/buerokratt/Buerokratt-Chatbot/tree/main/GUI
) responds to http://admin.test.buerokratt.ee/settings
- [x] [Training Module's](https://github.com/buerokratt/Training-Module) GUI responds to http://admin.test.buerokratt.ee/training
- [x] [Analytics Module's](https://github.com/buerokratt/Analytics-Module/tree/main/GUI
) GUI responds to http://admin.test.buerokratt.ee/analytics
- [x] http://test.buerokratt.ee responds to [Chat Widget](https://github.com/buerokratt/Chat-Widget)
- [ ] All requests to https://ruuter.test.buerokratt.ee/public/v1 are processed by [Ruuter v1](https://github.com/buerokratt/Ruuter-1.0)
- [ ] All requests to https://ruuter.test.buerokratt.ee/private/v2 are processed by [Ruuter v1](https://github.com/buerokratt/Ruuter-1.0)
- [ ] All requests to https://ruuter.test.buerokratt.ee/public/v2 are processed by [Ruuter v2](https://github.com/buerokratt/Ruuter)
- [ ] All requests to https://ruuter.test.buerokratt.ee/private/v2 are processed by [Ruuter v2](https://github.com/buerokratt/Ruuter)

**Comment by varmoh** [comment]
Test routing works as intended.
Re-config of nginx required to mirror criteria's

**Comment by turnerrainer** [comment]
https://github.com/buerokratt/Maintenance/commit/5b0717c2f19672026d7723e53a797ca753754482

**Comment by varmoh** [comment]
Currently both publick-ruuter v1 and v2 are separated by nginx conf.
http://ruuter.test.buerokratt.ee/v1/
http://ruuter.test.buerokratt.ee/v2/
Next step is to update conf to separate private and public ruuter with correct path (public/v1/ and public/v2/).
Also, in current conf SSL is not added.


Conf file is stored:
`/etc/nginx/conf.d`

```
server {
    listen 80;
#    access_log  /var/log/nginx/api.log; ## add where logs are stored
#    error_log   /var/log/nginx/api_error.log; ## add where logs are stored
    server_name ruuter.test.buerokratt.ee;

    location / {
        proxy_pass         http://x.x.x.x:8080/;
        proxy_redirect     off;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;

    }
    location /v2/ {

            rewrite ^/v2/?(.*) /$1 break;
            proxy_pass         http://x.x.x.x:8080/;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
    }

    location /v1/ {

            rewrite ^/v1/?(.*) /$1 break;
            proxy_pass         https://x.x.x.x:8091/;
            proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
    }
}
```

In `/etc/nginx/nginx.conf` check if:
```
include /etc/nginx/conf.d/*.conf;
```
is present. If not add it where you see
` http {
}`

**Comment by turnerrainer** [comment]
@varmoh 

- [ ] Resolve CORS errors
- [ ] Resolve MIME-types

See https://github.com/buerokratt/Buerokratt-Chatbot/blob/main/GUI/nginx/http-nginx.conf for reference

**Comment by turnerrainer** [comment]
Working at the moment, will move on to using Caddy and HAProxy from this point on.

**Comment by varmoh** [comment]
Chat widget requests between ruuter v1 and ruuter v2 can be routed using nginx server blocks.
When chat widget default endpoint is ruuter v2:
- Add under `ruuter` server block specific location and point it to ruuter v1
```
          location /custom-jwt-userinfo {
               rewrite ^/v1/?(.*) /$1 break;
               proxy_pass https://IP:PORT; ## Ruuter v1
