### ISSUE TITLE
Use FQDNs on TLS on test.buerokratt.ee 

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/NoOps#17]
AS A Product Owner of Bürokratt test environment
I WANT all services and components to be available as [FQDNs](https://en.wikipedia.org/wiki/Fully_qualified_domain_name) on TLS
SO THAT they would match production environment settings

### Acceptance Criteria

> Applies to all URIs based on the URIs listed below

- [x] https://test.buerokratt.ee
- [x] https://admin.test.buerokratt.ee
- [ ] https://ruuter.buerokratt.ee/public/v1
- [ ] https://ruuter.buerokratt.ee/private/v1
- [ ] https://ruuter.buerokratt.ee/public/v2
- [ ] https://ruuter.buerokratt.ee/private/v2
- [ ] https://tim.buerokratt.ee
- [ ] Resql by IP
- [ ] Data Mapper by IP

**Comment by varmoh** [comment]
Requires a self-signed server certification. Currently setting it up

**Comment by turnerrainer** [comment]
Done, using Caddy to provide TLS.
