### ISSUE TITLE
Deploy Training Module's DSLs to test environment

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/NoOps#23]
AS A DevOps
I WANT Trainig Module's DSLs to be deployed by a script
SO THAT I wouldn't have to do it manually

### Acceptance Criteria

- [x] Use https://github.com/buerokratt/Training-Module/tree/main/DSL as source code
- [x] All database schemas have been created and their updates deployed via Liquibase
- [x] OpenSearch up and running and indexes created by script
- [ ] Part of #15 
- [ ] Accessible via https://test.buerokratt.ee/training

**Comment by varmoh** [comment]
Training module OpenSearch has been deployed in a single node.
init.sh changed to mirror test environment and deployed.
All the data has bee indexed in the OpenSearch dashboard http://test.buerokratt.ee:5601

**Comment by varmoh** [comment]
Re-launched a fixed docker-compose for DSL mapping.
Requirement - a `train` database in Postgres must be present
`version: '3.9'
services:
  ruuter:
    container_name: privaat-ruuter_train
    image: priv-ruuter
    environment:
      - application.cors.allowedOrigins=http://test.buerokratt.ee:3002
      - application.httpCodesAllowList=200,201,202,400,401,403,500
    volumes:
      - ./Ruuter.private:/DSL
      - ./mock1:/mock1
    ports:
      - 8019:8080
    networks:
      - bykstack
 
  byk-liquibase-update:
    image: liquibase/liquibase
    command: --url=jdbc:postgresql://test.buerokratt.ee:5433/train?user=byk --password= --changelog-file=/master.yml update
    ports:
      - 8000:8000
    volumes:
      - ./Liquibase/master.yml:/liquibase/master.yml
      - ./Liquibase/changelog:/liquibase/changelog
    networks:
      - bykstack

  resql:
    container_name: resql_train
    image: resql_resql
    depends_on:
      - users_db
    environment:
      - sqlms.datasources.[0].name=byk
      - sqlms.datasources.[0].jdbcUrl=jdbc:postgresql://users_db:5433/train
      - sqlms.datasources.[0].username=byk
      - sqlms.datasources.[0].password=
      - logging.level.org.springframework.boot=INFO
    ports:
      - 8087:8082
    volumes:
      - ./Resql:/workspace/app/templates/byk
    networks:
      - bykstack


  data_mapper: 
     container_name: data_mapper_train
     image: dmapper
     volumes:
      - ./DMapper:/workspace/app/views/
     ports:
      - 3017:3000
     networks:
      - bykstack
networks:
  bykstack:
    name: bykstack
    driver: bridge
    driver_opts:                         
            com.docker.network.driver.mtu: 1400
`
