### ISSUE TITLE
Docker Compose to set up Postgres locally

### ISSUE THREAD

**Issue by Kristjanmn** [buerokratt/NoOps#31]
AS A DevOps
I WANT to set up Postgres database as a Docker container
SO THAT I would not have to set it up manually

> Moved from "Maintenance" project to "NoOps"
> Previously partially done, needs enhancement

### Acceptance Criteria

- [ ] Postgres database is installed locally by using a Dockerfile
- [ ] Sensitive parameters are configurable via Dockerfile
- [ ] Minimal, but comprehensive `README.md` to cover the whole process of installing Postgres as a separate instance
- [x] Docker Compose under [Postgres @ NoOps](https://github.com/buerokratt/NoOps/tree/31-docker-compose-to-set-up-postgres-locally/Docker/Components/Postgres)

**Comment by varmoh** [comment]
Pull request has been done for docker-compose
