### ISSUE TITLE
Updating bot in DEMO env

### ISSUE THREAD

**Issue by KlviG** [buerokratt/NoOps#42]
- [x]  Switching responses from "institution_bot" to actual answer from that institution.
- [x] Fixing data structure so that all intents, rules, responses  would have "insitution_" in front
- [x] Training new model and testing it in DEMO env

**Comment by KlviG** [comment]
demo bot has been trained and tested

**Comment by KlviG** [comment]
potentially have to increase "epochs" in bot config file

**Comment by turnerrainer** [comment]
Closed as has been for review for a long time without any negative feedback.
