### ISSUE TITLE
DNS for play.buerokratt.ee

### ISSUE THREAD

**Issue by varmoh** [buerokratt/NoOps#44]
AS A DevOps of Bürokratt play environment
I WANT the environment to have correct DNS records
SO THAT I an access it using domain name and SSL

### Acceptance Criteria

> Applies to all URIs based on the URIs listed below

- [x] https://play.buerokratt.ee
- [x] https://admin.play.buerokratt.ee
- [x] https://ruuter.play.buerokratt.ee
- [x] https://tim.play.buerokratt.ee

**Comment by varmoh** [comment]
Environment in Riigipilv has been built.
IP is 171.22.247.156
DNS ticket has been submitted.

**Comment by turnerrainer** [comment]
DNS for every component have been created but not yet implemented.
