### ISSUE TITLE
Allowlist of Bürokratt-specific resources

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/NoOps#97]
AS A DevOps
I WANT TO have a list of all Bürokratt-specific resources
SO THAT I could create my deployment scripts based on them

AS AN Architect
I WANT TO have a list of all Bürokratt-specific resources
SO THAT I could be confident that all the expected resources are deployed

### Acceptance Criteria

- [ ] Architect's input can be used by DevOps

#### Applications

|                    | Repo                                                           | Image                                            |
|--------------------|----------------------------------------------------------------|--------------------------------------------------|
| byk-ruuter-priv    | https://github.com/buerokratt/Ruuter                           | ghcr.io/buerokratt/ruuter:beta-2.0.0             |
| byk-ruuter-priv-v1 | https://github.com/buerokratt/Ruuter-1.0                       | ghcr.io/buerokratt/ruuter-1.0:beta-1.1.0         |
| byk-ruuter-pub     | https://github.com/buerokratt/Ruuter                           | ghcr.io/buerokratt/ruuter:beta-2.0.0             |
| byk-ruuter-pub-v1  | https://github.com/buerokratt/Ruuter-1.0                       | ghcr.io/buerokratt/ruuter-1.0:beta-1.1.0         |
| byk-dmapper        | https://github.com/buerokratt/DataMapper                       | ghcr.io/buerokratt/datamapper:prod-2.0.0         |
| byk-resql          | https://github.com/buerokratt/Resql                            | ghcr.io/buerokratt/resql:prod-2.1.0              |
| byk-tim            | https://github.com/buerokratt/TIM                              | ghcr.io/buerokratt/tim:prod-2.0.0                |
| byk-turvis         | https://github.com/buerokratt/Turvis                           | -                                                |
| byk-xtr            | https://github.com/buerokratt/XTR                              | -                                                |
| byk-dsl            | https://github.com/buerokratt/Buerokratt-DSL                   | ghcr.io/buerokratt/buerokratt-dsl:beta-1.0.0     |
| byk-chatbot        | https://github.com/RasaHQ/rasa                                 | rasa/rasa:3.0.13                                 |
| byk-chatbot-train  | https://github.com/RasaHQ/rasa                                 | rasa/rasa:3.0.13                                 |
| byk-widget-gui     | https://github.com/buerokratt/Chat-Widget                      | ghcr.io/buerokratt/chat-widget:beta-1.0.1        |
| byk-backoffice-gui | https://github.com/buerokratt/Buerokratt-Chatbot/tree/main/GUI | ghcr.io/buerokratt/buerokratt-chatbot:beta-1.0.0 |
| byk-training-gui   | https://github.com/buerokratt/Training-Module/tree/main/GUI    | ghcr.io/buerokratt/training-module:beta-1.0.0    |
| byk-services-gui   | https://github.com/buerokratt/Service-Module/tree/main/GUI     | ghcr.io/buerokratt/service-module:beta-1.0.0     |
| byk-analytics-gui  | https://github.com/buerokratt/Analytics-Module/tree/main/GUI   | ghcr.io/buerokratt/analytics-module:beta-1.0.0   |
| byk-anonymizer-gui | https://github.com/buerokratt/Data-Anonymizer                  | ghcr.io/buerokratt/data-anonymizer:beta-1.0.0    |

#### External storage

> Type `FS` = `File Storage`
> Type `OS` = `Object Storage`

|                       | Type | Dest                                                                                                                         |
|-----------------------|------|------------------------------------------------------------------------------------------------------------------------------|
| byk-dsl-ruuter        | FS   | `/byk-ruuter-priv/DSL/`, `/byk-ruuter-pub/DSL/`, `/byk-ruuter-priv-v1/configurations/`, `/byk-ruuter-pub-v1/configurations/` |
| byk-dsl-services      | FS   | `/byk-ruuter-priv/DSL/`, `/byk-ruuter-pubDSL/` |
| byk-dsl-resql         | FS   | `/byk-resql/DSL/` |
| byk-dsl-turvis           | FS   | - |
| byk-dsl-xtr           | FS   | - |
| byk-dsl-chatbot       | FS   | `/byk-chatbot/app/models/` |
| byk-dsl-chatbot-train | FS   | `/byk-chatbot-train/chatbot/` |

**Comment by varmoh** [comment]
byk-ruuter-priv - ghcr.io/buerokratt/ruuter:beta-2.0.0
byk-ruuter-pub- ghcr.io/buerokratt/ruuter:beta-2.0.0
byk-dmapper- ghcr.io/buerokratt/datamapper:prod-2.0.0
byk-resql- ghcr.io/buerokratt/resql:prod-2.1.0
byk-tim- ghcr.io/buerokratt/tim:prod-2.0.0

**Comment by varmoh** [comment]
byk-ruuter-priv-v1 - ghcr.io/buerokratt/ruuter-1.0:beta-1.1.0
byk-ruuter-pub-v1 - ghcr.io/buerokratt/ruuter-1.0:beta-1.1.0

**Comment by varmoh** [comment]
byk-anonymizer-gui - ghcr.io/buerokratt/data-anonymizer:beta-1.0.0

**Comment by KlviG** [comment]
Rasa image:
rasa/rasa:3.0.13

**Comment by turnerrainer** [comment]
In use.
